version: '{build}'
shallow_clone: true

platform: x64

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
# Makefile
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: make
    LANGUAGE: cc

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: make
    LANGUAGE: python

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: make
    LANGUAGE: java

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: make
    LANGUAGE: dotnet
# CMake
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: cmake
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

matrix:
  fast_finish: false

before_build:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "CI"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake --version
  - set PATH=C:\Python36-x64;%PATH%
  - tools\win\which.exe python.exe
  - python -V
  - python -m pip install virtualenv wheel six
  - tools\win\which.exe dotnet.exe
  - dotnet --info
  - set "JAVA_HOME=C:\Program Files\Java\jdk11"
  - set "PATH=C:\Program Files\Java\jdk11\bin;%PATH%"
  - java -version
  - if "%BUILDER%"=="cmake" cmake -H. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_DEPS:BOOL=ON -G "%CMAKE_GENERATOR%" || VER>NUL
  - if "%BUILDER%"=="make" del "C:\Program Files\Git\usr\bin\sh.exe"
  - if "%BUILDER%"=="make" tools\make.exe detect

build_script:
  - if "%BUILDER%"=="cmake" cmake --build build --config Release --target ALL_BUILD -- %MSBUILD_FLAGS%
  - if "%BUILDER%"=="make" tools\make.exe third_party
  - if "%BUILDER%"=="make" tools\make.exe help_%LANGUAGE%
  - if "%BUILDER%"=="make" tools\make.exe %LANGUAGE%
  - if "%BUILDER%"=="make" tools\make.exe test_%LANGUAGE%
  - if "%LANGUAGE%"=="cc" tools\make.exe test_fz

test_script:
  - if "%BUILDER%"=="cmake" cmake --build build --config Release --target RUN_TESTS

